name: 04 - Using-actions.yaml

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        #1. install deps of our react appl
        #2. execute automated steps.
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            
           # - name: Build Edwina Alpine web server
           #   run: |
           #     docker build -t edwina-nginx-server .github/workflows
           #     docker run -d --name eds-web-server -p 8080:80 edwina-nginx-server
           #     docker ps

            #Test the web Server
           # - name: Test Web Server
           #   run: |
           #       sleep 5
           #       curl http://localhost:8080