name: Publish image to Docker hub
on:
    [workflow_dispatch]

jobs:
    publich_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            - name: build image
              run: docker build . -t edwinasweeney/githubbuild:latest
            - name: push image to docker hub
              run: |
                docker push edwinasweeney/githubbuild:latest
