name: Publish image to Docker hub
on:
    [workflow_dispatch]

jobs:
    publich_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: build image
              run: docker build /workspaces/Action1/.github/workflows/dockerfilesapp -t edwinasweeney/githubbuild:latest
            - name: push image to docker hub
              run: |
                docker push edwinasweeney/githubbuild:latest
